server:
  port: 8088 # 서버포트

spring:
  profiles:
    active: local
  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/triple?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  # 패키지 명을 생략할 수 있도록 alias 설정
  type-aliases-package: com.triple.home.model
  mapper-locations: mybatis/mapper/**/*.xml
  # model 프로퍼티 camel case 설정
  configuration:
    map-underscore-to-camel-case: true

# mapper 로그레벨 설정 
logging:
  level:
    com.triple.home.mapper.ReviewMapper: TRACE


